### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by notgull** [corncobb/budget-app#2]
You really should put a license on this, because if you don't people can and will sue you. Especially for something like this. For instance, if I input the wrong values and ended up messing up my budget, I could sue you, as there is an implied warranty in your lack of license.

I would recommend the [BSD 3-Clause license](https://opensource.org/licenses/BSD-3-Clause) because it's the closest you can get to "do what ever you want, just don't sue me or advertise using me".

**Comment by corncobb** [comment]
Added license file and disclaimer. This repo is intended for learning purposes only and anyone can distribute, modify, and use this repo at their risk. The source code of this app is based on this [Udemy](https://www.udemy.com/share/101WfeBkcfeV1XQnQ=/) course. Real budget app may be made in the future.
